// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAHXOP41wCuzIBNcEBhKyVveQheOwWSAc',
    appId: '1:907834599183:web:f6241c1379915d764bc07a',
    messagingSenderId: '907834599183',
    projectId: 'project-d-start-of-everything',
    authDomain: 'project-d-start-of-everything.firebaseapp.com',
    storageBucket: 'project-d-start-of-everything.firebasestorage.app',
    measurementId: 'G-RXW9BGGQFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuPJdnA7o4zIz1n1WFHdeRx_9JlsTvWxE',
    appId: '1:907834599183:android:af85f8efa3ee1f164bc07a',
    messagingSenderId: '907834599183',
    projectId: 'project-d-start-of-everything',
    storageBucket: 'project-d-start-of-everything.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe6-bFFhyCqjeVFeY-771NTMRTBx9tYYw',
    appId: '1:907834599183:ios:fe5fef7ecfb3a6ff4bc07a',
    messagingSenderId: '907834599183',
    projectId: 'project-d-start-of-everything',
    storageBucket: 'project-d-start-of-everything.firebasestorage.app',
    iosBundleId: 'com.example.projectd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe6-bFFhyCqjeVFeY-771NTMRTBx9tYYw',
    appId: '1:907834599183:ios:fe5fef7ecfb3a6ff4bc07a',
    messagingSenderId: '907834599183',
    projectId: 'project-d-start-of-everything',
    storageBucket: 'project-d-start-of-everything.firebasestorage.app',
    iosBundleId: 'com.example.projectd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAHXOP41wCuzIBNcEBhKyVveQheOwWSAc',
    appId: '1:907834599183:web:b08788447894192a4bc07a',
    messagingSenderId: '907834599183',
    projectId: 'project-d-start-of-everything',
    authDomain: 'project-d-start-of-everything.firebaseapp.com',
    storageBucket: 'project-d-start-of-everything.firebasestorage.app',
    measurementId: 'G-9J6QFCXV4Y',
  );
}
